[package]
name = "argy"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
categories = ["command-line-interface"]
keywords = ["args", "arguments", "derive", "cli"]
readme = "README.md"

[dependencies]
argy_shared.workspace = true
argy_derive.workspace = true
rust-fuzzy-search = { version = "0.1.1", optional = true }

[dev-dependencies]
argy_complete = { version = "0.1.0", path = "../argy_complete" }
trybuild = "1.0.63"

[features]
default = ["help", "serde"]
help = ["argy_derive/help"]
serde = ["argy_shared/serde"]
fuzzy_search = ["dep:rust-fuzzy-search"]
