[workspace.package]
version = "0.1.19"
authors = ["Taylor Cramer <cramertj@google.com>", "Benjamin Brittain <bwb@google.com>", "Erick Tryzelaar <etryzelaar@google.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Derive-based argument parsing optimized for code size"
repository = "https://github.com/argy-rs/argy"

[workspace]
members = [
    "argy",
    "argy_derive",
    "argy_shared",
    "argy_complete",
]

[workspace.dependencies]
argy_shared = { version = "0.1.19", path = "argy_shared" }
argy_derive = { version = "0.1.19", path = "argy_derive" }
